sv-searchEngine/sv-searchEngine/Models/Attribute/OwnPropertyWeightAttribute.cs
namespace sv_searchEngine.Models.Attribute
{
    public class OwnPropertyWeightAttribute : System.Attribute
    {
        public int Weightage { get; set; }
        public OwnPropertyWeightAttribute(int weightage)
        {
            Weightage = weightage;

        }
    }
}

sv-searchEngine/sv-searchEngine/Models/Attribute/TransitivePropertyWeightAttribute.cs
namespace sv_searchEngine.Models.Attribute
{
    [System.AttributeUsage(System.AttributeTargets.Property ,
                       AllowMultiple = true)  // multiuse attribute  
    ]
    public class TransitivePropertyWeightAttribute : System.Attribute
    {
        public Type ParentObject { get; set; }
        public string PropertyName { get; set; }
        public int Weightage { get; set; }

        public TransitivePropertyWeightAttribute(Type parentObject, string propertyName, int weightage)
        {
            ParentObject = parentObject;
            PropertyName = propertyName;
            Weightage = weightage;

        }
    }
}

sv-searchEngine/sv-searchEngine/Models/DTOS/Building.cs
using sv_searchEngine.Models.Attribute;
using System;

namespace sv_searchEngine.Models.DTOS
{
    public class Building
    {
        public Guid Id { get; set; }
        [OwnPropertyWeightAttribute(7)]
        public string ShortCut { get; set; }
        [OwnPropertyWeightAttribute(9)]
        public string Name { get; set; } = null!;
        [OwnPropertyWeightAttribute(5)]
        public string Description { get; set; }
        public Weightage Weight { get; set; }

    }
}

sv-searchEngine/sv-searchEngine/Models/DTOS/Group.cs
using sv_searchEngine.Models.Attribute;

namespace sv_searchEngine.Models.DTOS
{
    public class Group
    {
        public Guid Id { get; set; }
        [OwnPropertyWeightAttribute(9)]
        public string Name { get; set; }
        [OwnPropertyWeightAttribute(5)]
        public string Description { get; set; }
        public Weightage Weight { get; set; }

    }
}

sv-searchEngine/sv-searchEngine/Models/DTOS/Lock.cs
using sv_searchEngine.Models.Attribute;

namespace sv_searchEngine.Models.DTOS
{
    public class Lock
    {
        public Guid Id { get; set; }
        [TransitivePropertyWeightAttribute(typeof(Building),"BuildingName", 8 )]
        [TransitivePropertyWeightAttribute(typeof(Building), "BuidingShortCut", 5)]
        public Guid BuildingId { get; set; }
        [OwnPropertyWeightAttribute(3)]
        public string Type { get; set; }
        [OwnPropertyWeightAttribute(10)]
        public string Name { get; set; }
        [OwnPropertyWeightAttribute(8)]
        public string Description { get; set; }
        [OwnPropertyWeightAttribute(6)]
        public string SerialNumber { get; set; }
        [OwnPropertyWeightAttribute(6)]
        public string Floor { get; set; }
        [OwnPropertyWeightAttribute(6)]
        public string RoomNumber { get; set; }

        public Weightage Weight { get; set; }
    }
}

sv-searchEngine/sv-searchEngine/Models/DTOS/Media.cs
using sv_searchEngine.Models.Attribute;

namespace sv_searchEngine.Models.DTOS
{
    public class Media
    {
        public Guid Id { get; set; }
        [TransitivePropertyWeightAttribute(typeof(Group), "GroupName", 8)]
        public Guid GroupId { get; set; }
        
        [OwnPropertyWeightAttribute(3)]
        public string Type { get; set; }
        [OwnPropertyWeightAttribute(10)]
        public string Owner { get; set; }
        [OwnPropertyWeightAttribute(8)]
        public object Description { get; set; }
        [OwnPropertyWeightAttribute(6)]
        public string SerialNumber { get; set; }
        public Weightage Weight { get; set; }

    }
}

sv-searchEngine/sv-searchEngine/Models/DTOS/Weightage.cs
namespace sv_searchEngine.Models.DTOS
{
    public class Weightage
    {
        public string Name { get; set; } = null!;
        public int Value { get; set; }
    }
}

sv-searchEngine/sv-searchEngine/Models/EntityModel.cs
using sv_searchEngine.Models.DTOS;


namespace sv_searchEngine.Models
{
    public class EntityModel
    {
        public IEnumerable<Building> Buildings { get; set; } = new List<Building>();
        public IEnumerable<Lock> Locks { get; set; } = new List<Lock>();
        public IEnumerable<Group> Groups { get; set; } = new List<Group>();
        public IEnumerable<Media> Media { get; set; } = new List<Media>();


    }
}

sv-searchEngine/sv-searchEngine/Models/ErrorViewModel.cs
namespace sv_searchEngine.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

sv-searchEngine/sv-searchEngine/Controllers/EntityController.cs
using Microsoft.AspNetCore.Mvc;
using sv_searchEngine.Models;
using sv_searchEngine.Services;

namespace sv_searchEngine.Controllers
{
    public class EntityController : Controller
    {
        private readonly IDataService _dataService;
        private readonly ISearchService _searchService;
        private EntityModel? _allData = null;
        public EntityController(IDataService dataService, ISearchService searchService)
        {
            _dataService = dataService;
            _searchService = searchService;
        }
        public async Task<ActionResult> Index(string searchCriteria)
        {
            if (_allData == null)
            {
                _allData = await _dataService.GetAllData();
            }

            if (!string.IsNullOrEmpty(searchCriteria) && _allData != null)
            {
                var data = _searchService.GetSearchedResults(searchCriteria, _allData);


                return View(data);

            }
            else
            {
                return View(_allData);
            }
        }

    }
}

sv-searchEngine/sv-searchEngine/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using sv_searchEngine.Models;
using System.Diagnostics;

namespace sv_searchEngine.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

sv-searchEngine/sv-searchEngine/Views/Entity/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Entity Page";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Index", "Entity", FormMethod.Get))
{
    <input type="text" name="searchCriteria" id="searchCriteria" />
    <input type="submit" title="search" alt="Search" value="Search" />
    @if (Model != null)
    {
        <legend>My Data Set: </legend>
        @if (Model.Buildings.Count > 0)
        {
            <legend>Building count:  @Model.Buildings.Count</legend>


            <table class="table" border="1" cellpadding="2" cellspacing="4">
                <tr>
                    <th>Building Name</th>
                    <th>ShortCut</th>
                    <th>Description</th>

                </tr>
                @foreach (var building in Model.Buildings)
                {
                    <tr>
                        <td>@building.Name</td>
                        <td>@building.ShortCut</td>
                        <td>@building.Description</td>

                    </tr>
                }
            </table>
        }
        @if (Model.Locks.Count > 0)
        {
            <legend>Locks count:  @Model.Locks.Count</legend>

            <table border="1" cellpadding="2" cellspacing="4">
                <tr>
                    <th>Type</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Serial Number</th>
                    <th>Floor</th>
                    <th>Room number</th>




                </tr>
                @foreach (var lck in Model.Locks)
                {
                    <tr>
                        <td>@lck.Name</td>
                        <td>@lck.Name</td>
                        <td>@lck.Description</td>
                        <td>@lck.SerialNumber</td>
                        <td>@lck.Floor</td>
                        <td>@lck.RoomNumber</td>


                    </tr>
                }
            </table>
        }


        @if (Model.Groups.Count > 0)
        {
            <legend>Group count:  @Model.Groups.Count</legend>

            <table border="1" cellpadding="2" cellspacing="4">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
                @foreach (var group in Model.Groups)
                {
                    <tr>
                        <td>@group.Name</td>
                        <td>@group.Description</td>
                    </tr>
                }
            </table>
        }


        @if (Model.Media.Count > 0)
        {
            <legend>Media count:  @Model.Media.Count</legend>

            <table border="1" cellpadding="2" cellspacing="4">
                <tr>
                    <th>Type</th>
                    <th>Owner</th>
                    <th>Description</th>
                    <th>Serial Number</th>
                </tr>
                @foreach (var media in Model.Media)
                {
                    <tr>
                      <td>@media.Type</td>
                      <td>@media.Owner</td>
                      <td>@media.Description</td>
                      <td>@media.SerialNumber</td>
                    </tr>
                }
            </table>
        }
    }          
}

sv-searchEngine/sv-searchEngine/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

sv-searchEngine/sv-searchEngine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sv_searchEngine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/sv_searchEngine.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="@Url.Content("../Styles/BaseStyles.css")"  type="text/css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">sv_searchEngine</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Entity" asp-action="Index">Entity</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - sv_searchEngine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>